name: hbd_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  html: ^0.15.5
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  dio: ^5.8.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0
  ticket_widget: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/bahia-logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: 'Cuprum'
      fonts:
       - asset: 'fonts/Cuprum.ttf'
       - asset: 'fonts/Cuprum-Italic.ttf'
         style: italic